services:
  senscritique_scrap:
    build: .
    volumes:
      - ./data:/mnt/data
      - ./senscritique_scrap:/senscritique_app/src/app

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./data:/usr/share/nginx/html/data
      - ./data/senscritique.json:/usr/share/nginx/html/data/senscritique.json
      - ./data/membres.json:/usr/share/nginx/html/data/membres.json