services:
  senscritique_scrap:
    build: .
    volumes:
      - $PWD/var:/mnt/data

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - $PWD/public:/usr/share/nginx/html
      - $PWD/var/senscritique.json:/usr/share/nginx/html/senscritique.json