services:
  senscritique_scrap:
    build: .
    volumes:
      - ./var:/mnt/data

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./var/senscritique.json:/usr/share/nginx/html/senscritique.json